language: ruby
rvm:
- 2.3

install:
  - gem install jekyll
  - gem install bundler
  - gem install html-proofer
  - gem install github-pages
script:
  - chmod +x scripts/build.sh
  - scripts/build.sh

# branch whitelist
branches:
  only:
    - master
  # - gh-pages     # test the gh-pages branch
  # - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer


deploy:
  skip_cleanup: true
  provider: script
  script:
    - chmod +x scripts/deploy.sh
    - scripts/deploy.sh
  on:
    branch: master
