language: ruby
rvm:
- 2.3

install:
  - gem install jekyll
  - gem install bundler
  - gem install html-proofer
  - bundle install
script:
  - chmod +x scripts/build.sh
  - scripts/build.sh

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  skip_cleanup: true
  provider: script
  script:
    # - echo "deploy starting ..."
    # - chmod +x scripts/deploy.sh
    - scripts/deploy.sh
  on:
    branch: master
